kind: pipeline
name: default

steps:
  - name: build
    image: nginx:latest
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    detach: true
    commands:
      - echo $PWD
      - ls /

  - name: docker
    image: plugins/docker
    #context: $PWD
    settings:
      repo: wimotek/trojan
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    tags:
      - latest
